# cloudbuild.yaml
steps:
  # build & push the container image
- name: "gcr.io/kaniko-project/executor:latest"
  args: ["--cache=true", "--cache-ttl=48h", "--destination=gcr.io/$PROJECT_ID/flask:latest"]
  # Deploy container image to Cloud Run
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  args: ['beta', 'run', 'deploy', 'flask', '--image', 'gcr.io/$PROJECT_ID/flask:latest', '--region', 'us-central1', '--allow-unauthenticated', '--platform', 'managed']